//HintName: Foobarbaz.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Kinen.Generator;

namespace Kinen.Test
{
    public partial class Foobarbaz : IOriginator
    {
        public IMemento CreateMemento()
        {
            return new FoobarbazMemento(PublicProperty, ProtectedProperty, _internalField, _privateField);
        }

        public void RestoreMemento(IMemento memento)
        {
            if(memento is not FoobarbazMemento concreteMemento) throw new ArgumentException("memento is not FoobarbazMemento");
            this.PublicProperty = concreteMemento.PublicProperty;
            this.ProtectedProperty = concreteMemento.ProtectedProperty;
            this._internalField = concreteMemento._internalField;
            this._privateField = concreteMemento._privateField;
        }

        private class FoobarbazMemento : IMemento
        {
            public FoobarbazMemento(string PublicProperty, string ProtectedProperty, string _internalField, string _privateField)
            {
                this.PublicProperty = PublicProperty;
                this.ProtectedProperty = ProtectedProperty;
                this._internalField = _internalField;
                this._privateField = _privateField;
            }

            public string _internalField { get; }

            public string _privateField { get; }

            public string ProtectedProperty { get; }

            public string PublicProperty { get; }
        }
    }
}
